# Generated by Django 4.2 on 2025-10-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_address_user_bonus_user_dpi_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
